defaultBaseImage: gcr.io/distroless/static:nonroot
defaultPlatforms:
- linux/arm64

builds:
- id: go-parking
  main: ./cmd/go-parking
  ldflags:
  - "-s"
  - "-w"
  - "-X main.version={{.Env.BUILD_VERSION}}"